version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    restart: always
    volumes:
      - /opt/storage:/htdocs/storage
    ports:
      - "43443:80"
