FROM nginx:1.23.0-alpine

WORKDIR /htdocs/

RUN chmod a+x /docker-entrypoint.sh

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/site.conf /etc/nginx/conf.d/default.conf
COPY ./www /htdocs/www
